### ISSUE TITLE
Correct IANA registry for CAA attributes

### ISSUE THREAD

**Issue by ounsworth** [vanbroup/acme-auto-discovery#8] opened 2023-07-20 01:33 UTC
From Fraser Tweedale:

> Regarding registration of CAA attributes (IANA considerations): they
need to be registered in the "Certification Authority Restriction
Properties" registry:
https://www.iana.org/assignments/pkix-parameters/pkix-parameters.xhtml#caa-properties

https://mailarchive.ietf.org/arch/msg/acme/o-P1fOtiIDyQvwkdXJJ93S5jZKI/

**Comment by vanbroup** [comment] 2023-07-20 18:26
This is a parameter and not a property, I don't think there is a registry for parameters. Parameters can be CA specific.

**Comment by vanbroup** [comment] 2023-09-01 14:45
Duplicate of #14

**Closed by vanbroup** 2023-09-01 14:45 UTC
